version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: task_manager_db
    restart: always
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=task_manager_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task_manager_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://dev_user:dev_password@db:5432/task_manager_db
      - SECRET_KEY=cheie_secreta_pentru_test_123
      - ALGORITHM=HS256
    depends_on:
      - db

volumes:
  postgres_data: