"""Updated the OnDelete action for the User

Revision ID: 778bda06ff59
Revises: c181e844c593
Create Date: 2026-02-25 18:55:43.314593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '778bda06ff59'
down_revision: Union[str, Sequence[str], None] = 'c181e844c593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('categories_owner_id_fkey'), 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tasks_owner_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_owner_id_fkey'), 'tasks', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key(op.f('categories_owner_id_fkey'), 'categories', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
