"""create_categories_table_and_update_tasks

Revision ID: 9d5a77c9b1b8
Revises: a74408122fb3
Create Date: 2026-02-22 17:22:13.131689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d5a77c9b1b8'
down_revision: Union[str, Sequence[str], None] = 'a74408122fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
