"""Added category for Tasks

Revision ID: bf8eba566f5d
Revises: 2c1e08d0b7e3
Create Date: 2026-02-19 16:01:55.103394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8eba566f5d'
down_revision: Union[str, Sequence[str], None] = '2c1e08d0b7e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'category')
    # ### end Alembic commands ###
